#!/usr/bin/env bash
#Sets nginx for listening to 80 port
apt-get update && apt-get install -y nginx
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
service nginx start

