#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# Update the package list
apt-get update

# Install Nginx without user interaction (assume yes to prompts)
apt-get install -y nginx

# Configure Nginx to listen on port 80 and serve a custom page
echo "Holberton School for the win!" > /var/www/html/index.html

# Restart Nginx to apply the changes
service nginx restart

exit 0
